// ── MEMORIAE EX MACHINA — Fragment Pool ───────────────────────────────────────
// Edit this file to add, remove, or change fragments.
// Each entry has three fields:
//   type:   personal_memory | internet_artifact | cultural_artifact | data_fragment
//   source: where the fragment comes from (displayed in the terminal)
//   text:   the fragment content — either a plain string, or an arrow function
//           () => `...` if it contains a date/year/time (regenerated each display)

// ── Date / time helpers ───────────────────────────────────────────────────────
const _y  = (a, b) => String(a + Math.floor(Math.random() * (b - a + 1)));
const _d  = (a, b) => `${_y(a,b)}-${String(1+Math.floor(Math.random()*12)).padStart(2,'0')}-${String(1+Math.floor(Math.random()*28)).padStart(2,'0')}`;
const _t  = ()     => `${String(Math.floor(Math.random()*24)).padStart(2,'0')}:${String(Math.floor(Math.random()*60)).padStart(2,'0')}:${String(Math.floor(Math.random()*60)).padStart(2,'0')}`;
const _t2 = ()     => `${String(Math.floor(Math.random()*24)).padStart(2,'0')}:${String(Math.floor(Math.random()*60)).padStart(2,'0')}`;
const _tc = ()     => `${String(Math.floor(Math.random()*2)).padStart(2,'0')}:${String(Math.floor(Math.random()*60)).padStart(2,'0')}:${String(Math.floor(Math.random()*60)).padStart(2,'0')}`;

const POOL = [

  // ── Personal memories ───────────────────────────────────────────────────────
  { type: 'personal_memory', source: 'slice of life',  text: '"the smell of that perfume"' },
  { type: 'personal_memory', source: 'slice of life',  text: '"a child\'s drawing, undated"' },
  { type: 'personal_memory', source: 'acoustic',  text: () => `"a voice on a phone recording, ${_y(1998,2018)}"` },
  { type: 'personal_memory', source: 'kinesthetic',       text: '"the weight of a dog"' },
  { type: 'personal_memory', source: 'spatial',           text: '"an address in a city that no longer exists"' },
  { type: 'personal_memory', source: 'linguistic',        text: '"a name yelled in the distance"' },
  { type: 'personal_memory', source: 'photographic',      text: '"the last photograph before the move"' },
  { type: 'personal_memory', source: 'photographic',      text: '"the first photograph after the move"' },
  { type: 'personal_memory', source: 'documentary',       text: '"a handwritten note, recipient unknown"' },
  { type: 'personal_memory', source: 'documentary',       text: '"a shopping list"' },
  { type: 'personal_memory', source: 'documentary',       text: '"a phone number on a post-it"' },
  { type: 'personal_memory', source: 'kinesthetic',       text: '"the sound of a fridge door"' },
  { type: 'personal_memory', source: 'spatial',           text: '"the neighbor\'s garden"' },
  { type: 'personal_memory', source: 'slice of life',  text: '"a birthday no one remembered"' },
  { type: 'personal_memory', source: 'temporal',          text: '"the summer ended"' },
  { type: 'personal_memory', source: 'spatial',           text: '"a key broken into a lock"' },
  { type: 'personal_memory', source: 'visual',    text: () => `"the view from a window, demolished ${_y(2004,2022)}"` },
  { type: 'personal_memory', source: 'linguistic',        text: '"a phone number memorized, owner unknown"' },
  { type: 'personal_memory', source: 'temporal',          text: '"the feeling of a particular afternoon"' },
  { type: 'personal_memory', source: 'temporal',          text: '"a burst of a feeling, 5 seconds"' },
  { type: 'personal_memory', source: 'temporal',          text: '"butterflies in the stomach"' },
  { type: 'personal_memory', source: 'slice of life',  text: '"a dream, partially remembered"' },
  { type: 'personal_memory', source: 'temporal',          text: '"the last day before the diagnosis"' },
  { type: 'personal_memory', source: 'visual',    text: '"a ladybug on a windowsill, June"' },
  { type: 'personal_memory', source: 'kinesthetic',       text: '"static electricity"' },
  { type: 'personal_memory', source: 'kinesthetic',       text: '"a touch of two shoulders, accidental"' },
  { type: 'personal_memory', source: 'spatial',           text: () => `"the forest at the edge of town, cleared ${_y(2008,2023)}"` },
  { type: 'personal_memory', source: 'documentary',       text: '"post-it note found behind a drawer — handwriting unknown"' },
  { type: 'personal_memory', source: 'visual',    text: '"a crow on a fence post, year unknown"' },
  { type: 'personal_memory', source: 'spatial',           text: () => `"the black locust grove — felled ${_y(2008,2023)}"` },
  { type: 'personal_memory', source: 'spatial',           text: '"the wooden pole at the end of the road"' },
  { type: 'personal_memory', source: 'visual',    text: '"butterflies in the garden, a specific afternoon"' },
  { type: 'personal_memory', source: 'visual',    text: '"clouds from a train window — roll of film, undeveloped"' },
  { type: 'personal_memory', source: 'documentary',       text: '"shoes by the door — whose, no longer certain"' },
  { type: 'personal_memory', source: 'spatial',           text: '"the keys — lock unknown, door unknown"' },
  { type: 'personal_memory', source: 'visual',    text: '"hands in a photograph, faces cropped out"' },
  { type: 'personal_memory', source: 'photographic',      text: '"a Duchenne smile"' },
  { type: 'personal_memory', source: 'visual',    text: '"a boomerang thrown in a field — never came back"' },
  { type: 'personal_memory', source: 'visual',    text: '"a frisbee on a roof, never retrieved"' },
  { type: 'personal_memory', source: 'visual',    text: '"a yellow frisbee thrown over the fence"' },

  // ── Internet artifacts — posts & text ───────────────────────────────────────
  { type: 'internet_artifact', source: 'twitter/x',         text: () => `"tweet deleted: ${_d(2007,2023)} ${_t()} UTC"` },
  { type: 'internet_artifact', source: 'twitter/x',         text: '"@[account suspended] — 2,341 tweets deleted"' },
  { type: 'internet_artifact', source: 'twitter/x',         text: '"retweet of suspended account — [ghost retweet]"' },
  { type: 'internet_artifact', source: 'twitter/x',         text: '"quote-tweet of a deleted tweet — context lost"' },
  { type: 'internet_artifact', source: 'twitter/x',         text: '"thread: 1/47 — original deleted, replies remain"' },
  { type: 'internet_artifact', source: 'twitter/x',         text: '"No more content creators. We need content destroyers." — @disxpix' },
  { type: 'internet_artifact', source: 'facebook',          text: '"facebook.com/[profile] — account deactivated"' },
  { type: 'internet_artifact', source: 'facebook',          text: () => `"facebook memory: post from ${_y(4,14)} years ago — user deleted"` },
  { type: 'internet_artifact', source: 'facebook',          text: '"event: 347 going, 812 interested — event deleted"' },
  { type: 'internet_artifact', source: 'instagram',         text: '"instagram.com/p/[id] — post no longer available"' },
  { type: 'internet_artifact', source: 'instagram',         text: '"instagram story: expired 24:00:00 ago"' },
  { type: 'internet_artifact', source: 'instagram',         text: '"instagram: account set to private — 4,201 posts hidden"' },
  { type: 'internet_artifact', source: 'instagram',         text: () => `"instagram.com/[user] — last post: ${_d(2013,2022)} — account abandoned"` },
  { type: 'internet_artifact', source: 'instagram',         text: '"Instagram Boomerang: [content unavailable]"' },
  { type: 'internet_artifact', source: 'tumblr',            text: () => `"tumblr.com/[blog] — deleted after NSFW purge, ${_y(2015,2021)}"` },
  { type: 'internet_artifact', source: 'tumblr',            text: '"reblog chain: 47,000 notes — original post deleted"' },
  { type: 'internet_artifact', source: 'reddit',            text: '"reddit.com/r/[sub]/comments/[id] — [deleted]"' },
  { type: 'internet_artifact', source: 'reddit',            text: '"comment: [removed] — 2,847 upvotes — mod reason: unknown"' },
  { type: 'internet_artifact', source: 'reddit',            text: '"reddit.com/r/[sub] — subreddit banned"' },
  { type: 'internet_artifact', source: '4chan',              text: '"4chan.org/[board]/thread/[id] — 404 (auto-pruned)"' },
  { type: 'internet_artifact', source: 'forum',             text: '"thread deleted by moderator — reason: none given"' },
  { type: 'internet_artifact', source: 'forum',             text: '"post [deleted] — 847 replies orphaned"' },
  { type: 'internet_artifact', source: 'forum',             text: () => `"phpBB forum: last post ${_d(2005,2017)} — server expired"` },
  { type: 'internet_artifact', source: 'livejournal',       text: '"livejournal.com/users/[name] — journal deleted"' },
  { type: 'internet_artifact', source: 'myspace',           text: '"myspace.com/[user] — profile deleted"' },
  { type: 'internet_artifact', source: 'myspace',           text: '"myspace: top 8 — all accounts deleted"' },
  { type: 'internet_artifact', source: 'blog',              text: () => `"blog: last post ${_d(2006,2018)} — 'will write more soon'"` },
  { type: 'internet_artifact', source: 'blog',              text: '"blogger.com/[blog] — blog has been removed"' },
  { type: 'internet_artifact', source: 'blog',              text: () => `"RSS feed: last updated ${_d(2007,2019)} — feed abandoned"` },
  { type: 'internet_artifact', source: 'wikipedia',         text: '"wikipedia: article deleted — \'did not meet notability guidelines\'"' },
  { type: 'internet_artifact', source: 'wikipedia',         text: '"wikipedia: edit by [user] — reverted, reason: vandalism"' },
  { type: 'internet_artifact', source: 'discord',           text: '"discord server: [name] — invite expired"' },
  { type: 'internet_artifact', source: 'discord',           text: '"discord: message [deleted] — 23 reactions"' },
  { type: 'internet_artifact', source: 'discord',           text: '"discord: channel #memories — server deleted"' },
  { type: 'internet_artifact', source: 'snapchat',          text: '"snapchat: story expired — 23:59:59 → 00:00:00"' },
  { type: 'internet_artifact', source: 'tiktok',            text: '"tiktok.com/@[user]/video/[id] — removed"' },
  { type: 'internet_artifact', source: 'tiktok',            text: '"tiktok: 2.1M views — video removed by creator"' },

  // ── Internet artifacts — images ─────────────────────────────────────────────
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'me at the beach, summer 2003"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'us at the concert\'"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'graduation day\'"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'the old house\'"' },
  { type: 'internet_artifact', source: 'broken image',      text: () => `"[broken image] — alt: 'mom, ${_y(1975,1997)}'"` },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: [no alt text provided]"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — 1,204 likes before deletion"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — 3 likes before deletion"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — 3 likes, 15 comments before deletion"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — no likes, 2 comments before deletion"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'clouds from the meadow\'"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'just butterflies"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'cake, someone\'s birthday\'"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'shoes by the door\'"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'crow on the column\'"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'hands\'"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'lonely scarecrow\'"' },
  { type: 'internet_artifact', source: 'broken image',      text: '"[broken image] — alt: \'black locust in bloom\'"' },
  { type: 'internet_artifact', source: 'photobucket',       text: '"photobucket.com/[album] — bandwidth limit exceeded"' },
  { type: 'internet_artifact', source: 'photobucket',       text: () => `"photobucket: image replaced with ransom notice, ${_y(2015,2020)}"` },
  { type: 'internet_artifact', source: 'imgur',             text: '"imgur.com/[id] — image removed by user"' },
  { type: 'internet_artifact', source: 'imgur',             text: '"imgur.com/[id] — removed for violating terms"' },
  { type: 'internet_artifact', source: 'flickr',            text: '"flickr.com/photos/[user] — account closed"' },
  { type: 'internet_artifact', source: 'flickr',            text: '"flickr: 1,000-photo free limit — oldest photos deleted"' },
  { type: 'internet_artifact', source: 'image hosting',     text: '"thumbnail only — original 4K file: missing"' },
  { type: 'internet_artifact', source: 'image hosting',     text: '"screenshot of a post — resolution too low to read"' },
  { type: 'internet_artifact', source: 'image hosting',     text: '"image: 1×1 tracking pixel — [1.1 kB] — campaign ended"' },
  { type: 'internet_artifact', source: 'NFT',               text: '"NFT: token exists on-chain — media file: 404"' },
  { type: 'internet_artifact', source: 'NFT',               text: '"NFT: \'permanent\' artwork — IPFS node offline"' },

  // ── Internet artifacts — video ──────────────────────────────────────────────
  { type: 'internet_artifact', source: 'youtube',           text: '"youtube.com/watch?v=[id] — video unavailable"' },
  { type: 'internet_artifact', source: 'youtube',           text: '"youtube.com/watch?v=[id] — account terminated"' },
  { type: 'internet_artifact', source: 'youtube',           text: '"youtube: video privated — 14M views preserved nowhere"' },
  { type: 'internet_artifact', source: 'vine',              text: () => `"vine.co/v/[id] — service discontinued ${_y(2015,2019)}"` },
  { type: 'internet_artifact', source: 'vine',              text: '"vine: 6-second loop — all servers offline"' },
  { type: 'internet_artifact', source: 'periscope',         text: () => `"periscope.tv/[user] — service shutdown ${_y(2019,2023)}"` },
  { type: 'internet_artifact', source: 'flash',             text: '"flash animation: [title unknown] — plugin unsupported"' },
  { type: 'internet_artifact', source: 'flash',             text: '"newgrounds.com/portal/view/[id] — removed by author"' },
  { type: 'internet_artifact', source: 'flash',             text: '"flash game: [title unknown] — ruffle.rs: incompatible"' },

  // ── Internet artifacts — infrastructure ─────────────────────────────────────
  { type: 'internet_artifact', source: 'web archive',       text: '"geocities.com/~personal/memories — 404"' },
  { type: 'internet_artifact', source: 'web archive',       text: () => `"cached: ${_d(2005,2020)} ${_t2()} — page unavailable"` },
  { type: 'internet_artifact', source: 'web archive',       text: '"wayback machine: 0 snapshots available for this URL"' },
  { type: 'internet_artifact', source: 'web archive',       text: () => `"wayback machine: page saved once — ${_d(2000,2015)}"` },
  { type: 'internet_artifact', source: 'web archive',       text: () => `"internet archive: file corrupted — last known good: ${_y(2004,2018)}"` },
  { type: 'internet_artifact', source: 'link rot',          text: () => `"hyperlink target removed — est. ${_y(2005,2018)}"` },
  { type: 'internet_artifact', source: 'link rot',          text: '"broken link in a broken link in a broken link"' },
  { type: 'internet_artifact', source: 'link rot',          text: '"broken embed — original tweet no longer exists"' },
  { type: 'internet_artifact', source: 'instant messaging', text: '"ICQ: 3847291 — last seen: [corrupted]"' },
  { type: 'internet_artifact', source: 'instant messaging', text: () => `"AIM screenname: xX_user_Xx — offline since ${_y(2014,2020)}"` },
  { type: 'internet_artifact', source: 'instant messaging', text: () => `"MSN Messenger: [email] — last seen: ${_y(2009,2016)}"` },
  { type: 'internet_artifact', source: 'file sharing',      text: () => `"megaupload.com/[id] — seized ${_y(2010,2015)}"` },
  { type: 'internet_artifact', source: 'file sharing',      text: () => `"rapidshare.com/[id] — service discontinued ${_y(2012,2018)}"` },
  { type: 'internet_artifact', source: 'music',             text: '"soundcloud.com/[user]/[track] — track deleted"' },
  { type: 'internet_artifact', source: 'email',             text: '"newsletter: unsubscribe link active — content gone"' },
  { type: 'internet_artifact', source: 'location tech',     text: '"AirTag: last seen 847 days ago — location: unknown"' },
  { type: 'internet_artifact', source: 'social media',      text: () => `"#[trending ${_y(2009,2021)}] — 0 results"` },
  { type: 'internet_artifact', source: 'social media',      text: () => `"google+: community dissolved ${_y(2017,2021)}"` },

  // ── Cultural / literary ─────────────────────────────────────────────────────
  { type: 'cultural_artifact', source: 'cinema',            text: () => `35mm film reel, unlabeled, est. ${_y(1963,1986)}` },
  { type: 'cultural_artifact', source: 'cinema',            text: 'Super 8, 3 minutes — sound track missing' },
  { type: 'cultural_artifact', source: 'photography',       text: 'Polaroid, faded to white — image unrecoverable' },
  { type: 'cultural_artifact', source: 'photography',       text: 'daguerreotype — surface oxidized, subject unknown' },
  { type: 'cultural_artifact', source: 'photography',       text: 'photographic negative — no corresponding print found' },
  { type: 'cultural_artifact', source: 'music',             text: 'analog tape recording, unlabeled, degraded' },
  { type: 'cultural_artifact', source: 'music',             text: () => `field recording, ${_y(1960,1978)} — ambient sound, location unknown` },
  { type: 'cultural_artifact', source: 'manuscript',        text: 'manuscript, ink faded, language uncertain' },
  { type: 'cultural_artifact', source: 'manuscript',        text: () => `letter, unsent — found inside a book, ${_y(1968,1998)}` },
  { type: 'cultural_artifact', source: 'manuscript',        text: 'diary, last entry: Tuesday — year illegible' },
  { type: 'cultural_artifact', source: 'VHS',               text: 'VHS tape, unlabeled — magnetic decay 78%' },
  { type: 'cultural_artifact', source: 'oral tradition',    text: () => `a funny story — last told ${_y(2008,2023)}` },

  // ── Abstract / data ─────────────────────────────────────────────────────────
  { type: 'data_fragment', source: 'system log',      text: 'CHECKSUM: f4e2a1b9c3d7 [MISMATCH — original lost]' },
  { type: 'data_fragment', source: 'memory scan',     text: 'fragment 0x3A2F — partially corrupted, 34% readable' },
  { type: 'data_fragment', source: 'memory scan',     text: 'fragment 0x7F11 — origin: pre-2010 web' },
  { type: 'data_fragment', source: 'entropy monitor', text: 'signal decay: 23% loss detected since last cycle' },
  { type: 'data_fragment', source: 'unknown',         text: 'NULL — origin unknown, content indeterminate' },
  { type: 'data_fragment', source: 'binary stream',   text: '1001 0100 1101... [truncated at 2048 bits]' },
  { type: 'data_fragment', source: 'geolocation',     text: '47.4979° N, 19.0402° E — timestamp: corrupted' },
  { type: 'data_fragment', source: 'hash registry',   text: 'hash collision — fragment may not be unique' },
  { type: 'data_fragment', source: 'network trace',   text: 'packet loss: 18% — retransmission failed' },
  { type: 'data_fragment', source: 'codec',           text: 'encoding: unknown — attempting reconstruction' },
  { type: 'data_fragment', source: 'storage',         text: 'RAID array: 1 of 3 drives failed — parity lost' },
  { type: 'data_fragment', source: 'storage',         text: 'backup tape: read error at sector 0x00041A' },
  { type: 'data_fragment', source: 'cloud storage',   text: 'cloud account deleted — recovery window expired' },
  { type: 'data_fragment', source: 'codec',           text: 'lossy compression: generation 7 — original unrestorable' },
  { type: 'data_fragment', source: 'metadata',        text: 'EXIF data stripped — location, date: absent' },
  { type: 'data_fragment', source: 'filesystem',      text: 'bit rot: 0.003% per year — estimated loss: 14 years' },
  { type: 'data_fragment', source: 'filesystem',      text: 'inode: 0x0000 — directory entry with no data' },
  { type: 'data_fragment', source: 'system log',      text: 'log entry: [REDACTED] — clearance level: expired' },
  { type: 'data_fragment', source: 'temp file',       text: '~$tmp_memory_0041.dat — unsaved, process terminated' },
  { type: 'data_fragment', source: 'cache',           text: 'cache entry evicted — TTL expired 00:00:03 ago' },
  { type: 'data_fragment', source: 'archive',         text: 'archive.zip: CRC mismatch — extraction failed' },
  { type: 'data_fragment', source: 'database',        text: 'database orphan — foreign key references nothing' },
  { type: 'data_fragment', source: 'archive',         text: 'a zip bomb — extraction aborted' },

];
